name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build and publish
        run: npx electron-vite build && npx electron-builder --config electron-builder.yml --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAIN_VITE_HARVEST_CLIENT_ID: ${{ secrets.MAIN_VITE_HARVEST_CLIENT_ID }}
          MAIN_VITE_HARVEST_CLIENT_SECRET: ${{ secrets.MAIN_VITE_HARVEST_CLIENT_SECRET }}
          MAIN_VITE_JIRA_CLIENT_ID: ${{ secrets.MAIN_VITE_JIRA_CLIENT_ID }}
          MAIN_VITE_JIRA_CLIENT_SECRET: ${{ secrets.MAIN_VITE_JIRA_CLIENT_SECRET }}
